name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    environment: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Get current version from GitHub environment variable
        id: get_version
        run: |
          VERSION=$(curl -H "Authorization: Bearer ${{ secrets.TOKEN_MOD_GOD }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/ItsCottin/modulum/environments/github-pages/variables/VERSION \
                        | jq -r '.value')
          echo "current_version=$VERSION" >> $GITHUB_ENV
      - name: Increment version
        id: increment_version
        run: |
          CURRENT_VERSION=${{ env.current_version }}
          
          # Increment the version and format with leading zeros
          NEW_VERSION=$(printf "%03d" $((10#$CURRENT_VERSION + 1)))
          
          # Convert to semver format x.x.x
          SEMVER_VERSION="${NEW_VERSION:0:1}.${NEW_VERSION:1:1}.${NEW_VERSION:2:1}"
          
          echo "New version: $SEMVER_VERSION"
          
          # Update package.json
          jq --arg new_version "$SEMVER_VERSION" '.version = $new_version' package.json > tmp.$$.json && mv tmp.$$.json package.json
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "semver_version=$SEMVER_VERSION" >> $GITHUB_ENV

      - name: Update environment variable VERSION
        run: |
          NEW_VERSION=${{ env.new_version }}
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.TOKEN_MOD_GOD }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"VERSION\", \"value\":\"$NEW_VERSION\"}" \
            https://api.github.com/repos/ItsCottin/modulum/environments/github-pages/variables/VERSION

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    environment: github-pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_MOD_GOD }}
          publish_dir: ./dist
